# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.put_room_request import PutRoomRequest  # noqa: E501

class TestPutRoomRequest(unittest.TestCase):
    """PutRoomRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutRoomRequest:
        """Test PutRoomRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutRoomRequest`
        """
        model = PutRoomRequest()  # noqa: E501
        if include_optional:
            return PutRoomRequest(
                id = 56,
                room_number = '',
                building_id = 56,
                area_squarefeet = 56,
                current_vlan = 56,
                is_active = True,
                is_virtual = True
            )
        else:
            return PutRoomRequest(
                id = 56,
                room_number = '',
                building_id = 56,
                area_squarefeet = 56,
                current_vlan = 56,
                is_active = True,
                is_virtual = True,
        )
        """

    def testPutRoomRequest(self):
        """Test PutRoomRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
