# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.tenancy import Tenancy  # noqa: E501

class TestTenancy(unittest.TestCase):
    """Tenancy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tenancy:
        """Test Tenancy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tenancy`
        """
        model = Tenancy()  # noqa: E501
        if include_optional:
            return Tenancy(
                id = 56,
                room_id = 56,
                tenant_id = '',
                roomid = 56,
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                start_source = '',
                end_source = '',
                created_at = '',
                last_updated = ''
            )
        else:
            return Tenancy(
                room_id = 56,
                tenant_id = '',
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                start_source = '',
        )
        """

    def testTenancy(self):
        """Test Tenancy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
