# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.building_coordinate import BuildingCoordinate  # noqa: E501

class TestBuildingCoordinate(unittest.TestCase):
    """BuildingCoordinate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildingCoordinate:
        """Test BuildingCoordinate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildingCoordinate`
        """
        model = BuildingCoordinate()  # noqa: E501
        if include_optional:
            return BuildingCoordinate(
                type = '',
                coordinates = [
                    1.337
                    ]
            )
        else:
            return BuildingCoordinate(
        )
        """

    def testBuildingCoordinate(self):
        """Test BuildingCoordinate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
