# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class PutRoomRequest(BaseModel):
    """
    PutRoomRequest
    """
    id: StrictInt = Field(...)
    room_number: StrictStr = Field(...)
    building_id: StrictInt = Field(...)
    area_squarefeet: StrictInt = Field(...)
    current_vlan: StrictInt = Field(...)
    is_active: StrictBool = Field(...)
    is_virtual: StrictBool = Field(...)
    __properties = ["id", "room_number", "building_id", "area_squarefeet", "current_vlan", "is_active", "is_virtual"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PutRoomRequest:
        """Create an instance of PutRoomRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PutRoomRequest:
        """Create an instance of PutRoomRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PutRoomRequest.parse_obj(obj)

        _obj = PutRoomRequest.parse_obj({
            "id": obj.get("id"),
            "room_number": obj.get("room_number"),
            "building_id": obj.get("building_id"),
            "area_squarefeet": obj.get("area_squarefeet"),
            "current_vlan": obj.get("current_vlan"),
            "is_active": obj.get("is_active"),
            "is_virtual": obj.get("is_virtual")
        })
        return _obj


