# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class Room(BaseModel):
    """
    Room
    """
    id: Optional[StrictInt] = Field(None, alias="Id")
    building_id: StrictInt = Field(...)
    room_number: StrictStr = Field(...)
    area_squarefeet: Optional[StrictInt] = None
    default_vlan: StrictInt = Field(...)
    current_vlan: Optional[StrictInt] = None
    created_at: Optional[StrictStr] = None
    last_updated: Optional[StrictStr] = None
    __properties = ["Id", "building_id", "room_number", "area_squarefeet", "default_vlan", "current_vlan", "created_at", "last_updated"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Room:
        """Create an instance of Room from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Room:
        """Create an instance of Room from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Room.parse_obj(obj)

        _obj = Room.parse_obj({
            "id": obj.get("Id"),
            "building_id": obj.get("building_id"),
            "room_number": obj.get("room_number"),
            "area_squarefeet": obj.get("area_squarefeet"),
            "default_vlan": obj.get("default_vlan"),
            "current_vlan": obj.get("current_vlan"),
            "created_at": obj.get("created_at"),
            "last_updated": obj.get("last_updated")
        })
        return _obj


