# coding: utf-8

"""
    Wavenet Connected API

    Provides a primary resource for buildings, room tenancies for Wavenet connected customers, includes other information such as VLAN information and addresses

    The version of the OpenAPI document: 2.5.x
    Contact: development@wavenetuk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date

from pydantic import BaseModel, Field, StrictInt, StrictStr

class UpdateTenancyRequest(BaseModel):
    """
    UpdateTenancyRequest
    """
    id: StrictInt = Field(...)
    tenant_id: StrictStr = Field(...)
    room_id: StrictInt = Field(...)
    start_date: date = Field(...)
    end_date: date = Field(...)
    start_source: StrictStr = Field(...)
    end_source: StrictStr = Field(...)
    __properties = ["id", "tenant_id", "room_id", "start_date", "end_date", "start_source", "end_source"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateTenancyRequest:
        """Create an instance of UpdateTenancyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateTenancyRequest:
        """Create an instance of UpdateTenancyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateTenancyRequest.parse_obj(obj)

        _obj = UpdateTenancyRequest.parse_obj({
            "id": obj.get("id"),
            "tenant_id": obj.get("tenant_id"),
            "room_id": obj.get("room_id"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "start_source": obj.get("start_source"),
            "end_source": obj.get("end_source")
        })
        return _obj


